version: '3.7'

services:
  web:
    build: ./
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/coinmena/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=coinmena_user
      - POSTGRES_PASSWORD=coinmena_password
      - POSTGRES_DB=coinmena
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
