# Generated by Django 3.2.2 on 2021-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency_code', models.CharField(max_length=5)),
                ('source_currency_name', models.CharField(max_length=50)),
                ('target_currency_code', models.CharField(max_length=5)),
                ('target_currency_name', models.CharField(max_length=50)),
                ('exchange_rate', models.FloatField()),
                ('last_refreshed', models.DateTimeField()),
            ],
        ),
    ]
