# Generated by Django 3.2.2 on 2021-05-08 09:06

from django.db import migrations
from django_celery_beat import models as beat_models


def forwards(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat.PeriodicTask')
    IntervalSchedule = apps.get_model('django_celery_beat.IntervalSchedule')
    schedule, created = IntervalSchedule.objects.get_or_create(
        every=1,
        period=beat_models.IntervalSchedule.HOURS,
    )

    PeriodicTask.objects.create(
        interval=schedule,
        name='Fetch rates for BTC to USD',
        task='rates.tasks.fetch_latest_rate_btc_to_usd'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
